# Use postgres/admin user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 54320:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - db_nw
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=5032
      # - SCRIPT_NAME=/pgadmin
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - 5050:5032
      # - 80:80
    depends_on:
      - db
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge

volumes:
  pgdata:
